### PR TITLE
BP-2354: Revocation result

### PR DESCRIPTION
**Pull request by alnicoli**
Revocation result without revocation in progress

### CODE REVIEW

**Comment by bauer00** [comment]
grafik

The red background isn't transparent.
Btw. the blur-function doesn't work yet on Firefox (needs to be enabled by the user).

**Review by bauer00 — APPROVED** [review]
Rest looks good

**Comment by alnicoli** [comment]
I think with the latest changes it looks OK now on firefox. What do you think?

**Comment by bauer00** [comment]
I think the opacity needs to be 0.95 to not distract the text in front.

I've just found a workaround for the "frosted glass" effect with the filter method instead of backdrop-filter, which is better supported:
https://webdesign.tutsplus.com/tutorials/how-to-create-a-frosted-glass-effect-in-css--cms-32535
https://caniuse.com/css-filters

**Comment by alnicoli** [comment]
I saw the method with background-image as well but in the end it won't work in our case because we want to blur a div and not an image. The blur effect comes from the filter: blur() which only works on images.

Ok let me try with .95

**Comment by bauer00** [comment]
Ah I see, it looks now good without backdrop-filter. If backdrop-filter is working, the effect is now almost invisible, let's hope firefox enables that feature soon by default.

**Comment by alnicoli** [comment]
Yes the effect is minimal but i guess we have no other choice

**Pull request merged**
